@echo off
echo Poliklinik Sistemi Baslatiliyor...

echo Backend (C#) ayaga kaldiriliyor...
start cmd /k "cd Backend\Poliklinik && dotnet run"

echo Frontend (Angular) ayaga kaldiriliyor...
start cmd /k "cd Frontend && ng serve --open"